Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -46,10 +46,10 @@ jobs:
           echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
           echo "buildPython=\"/usr/bin/python3.8\"" >> local.properties
   # 验证 Python 路径
-      - name: Debug Python path
+      - name: Check Python path
         run: |
-          which python3.8
-          python3.8 --version
+          which python3.8 || echo "Python 3.8 not found"
+          which python3   || echo "Python 3 not found"
         
       - name: Check New Commit
         run: |
